In [1]:
import numpy as np

In [2]:
a = np.array ([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
b = a[2:4, 1:2]
b

array([[10],
       [14]])

In [4]:
a[1, :]

array([5, 6, 7, 8])

In [5]:
a[a>10]

array([11, 12, 13, 14, 15, 16])

# ***Data Types***

In [6]:
x = np.array([1, 2])
print(x.dtype)

int64


# ***Only Type***

In [7]:
type(x)

numpy.ndarray

In [9]:
x = np.array([1, 2], dtype=np.float64)
print(x, x.dtype)

[1. 2.] float64


In [10]:
x.dtype

dtype('float64')

In [13]:
x = np.array([[1,2], [3,4]], dtype = np.float64)
y = np.array([[1,2], [3,4]], dtype = np.float64)
print(x)

[[1. 2.]
 [3. 4.]]


In [14]:
x, x.shape

(array([[1., 2.],
        [3., 4.]]),
 (2, 2))

In [15]:
x.T, x.T.shape

(array([[1., 3.],
        [2., 4.]]),
 (2, 2))

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


# ***Broadcasting***

In [17]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
y = [[1, 0, 1]]
p = x+y
print(p)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 0, 1]]


In [19]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 0, 1])
p = x + y
p

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])