In [2]:
import numpy as np

In [3]:
a = np.array ([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
b = a[2:4, 1:2]
b

array([[10],
       [14]])

In [5]:
a[1, :]

array([5, 6, 7, 8])

In [6]:
a[a>10]

array([11, 12, 13, 14, 15, 16])

# ***Data Types***

In [7]:
x = np.array([1, 2])
print(x.dtype)

int64


# ***Only Type***

In [8]:
type(x)

numpy.ndarray

In [9]:
x = np.array([1, 2], dtype=np.float64)
print(x, x.dtype)

[1. 2.] float64


In [10]:
x.dtype

dtype('float64')

In [11]:
x = np.array([[1,2], [3,4]], dtype = np.float64)
y = np.array([[1,2], [3,4]], dtype = np.float64)
print(x)

[[1. 2.]
 [3. 4.]]


In [12]:
x, x.shape

(array([[1., 2.],
        [3., 4.]]),
 (2, 2))

In [13]:
x.T, x.T.shape

(array([[1., 3.],
        [2., 4.]]),
 (2, 2))

In [14]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


# ***Broadcasting***

In [15]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
y = [[1, 0, 1]]
p = x+y
print(p)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 0, 1]]


In [16]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 0, 1])
p = x + y
p

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 2, 3])
p = x.T + y
p

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[-1, -2]])
p = x.T + y
p

array([[0, 2],
       [1, 3],
       [2, 4]])

In [19]:
webpage = "https://en.wikipedia.org/wiki/Red_states_and_blue_states"

In [20]:
import requests
import bs4
import pandas as pd


Mozilla/5.0

Historical label for compatibility (almost all browsers include this)

(Windows NT 10.0; Win64; x64)

Says you're using:

Windows 10

64-bit system

AppleWebKit/537.36

Browser engine (used by Chrome, Safari, etc.)

(KHTML, like Gecko)

Compatibility note for rendering engines

Chrome/120.0.0.0

Pretends you're using Chrome version 120

Safari/537.36

Another compatibility tag

In [21]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36"
}


In [22]:
web_page = bs4.BeautifulSoup(requests.get(webpage, {}, headers=headers).text, 'lxml')

In [23]:
web_page

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" dir="ltr" lang="en">
<head>
<meta charset="utf-8"/>
<title>Red states and blue states - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpre

In [24]:
tables = web_page.find_all(name='table', attrs={'class': 'wikitable'})
tables

[<table class="wikitable sortable" style="text-align:center">
 <tbody><tr>
 <th>Year
 </th>
 <th style="text-align:center; width:6.67%;"><a href="/wiki/1972_United_States_presidential_election" title="1972 United States presidential election">1972</a>
 </th>
 <th style="text-align:center; width:6.67%;"><a href="/wiki/1976_United_States_presidential_election" title="1976 United States presidential election">1976</a>
 </th>
 <th style="text-align:center; width:6.67%;"><a href="/wiki/1980_United_States_presidential_election" title="1980 United States presidential election">1980</a>
 </th>
 <th style="text-align:center; width:6.67%;"><a href="/wiki/1984_United_States_presidential_election" title="1984 United States presidential election">1984</a>
 </th>
 <th style="text-align:center; width:6.67%;"><a href="/wiki/1988_United_States_presidential_election" title="1988 United States presidential election">1988</a>
 </th>
 <th style="text-align:center; width:6.67%;"><a href="/wiki/1992_United_S

In [43]:
table = tables[0]
table

<table class="wikitable sortable" style="text-align:center">
<tbody><tr>
<th>Year
</th>
<th style="text-align:center; width:6.67%;"><a href="/wiki/1972_United_States_presidential_election" title="1972 United States presidential election">1972</a>
</th>
<th style="text-align:center; width:6.67%;"><a href="/wiki/1976_United_States_presidential_election" title="1976 United States presidential election">1976</a>
</th>
<th style="text-align:center; width:6.67%;"><a href="/wiki/1980_United_States_presidential_election" title="1980 United States presidential election">1980</a>
</th>
<th style="text-align:center; width:6.67%;"><a href="/wiki/1984_United_States_presidential_election" title="1984 United States presidential election">1984</a>
</th>
<th style="text-align:center; width:6.67%;"><a href="/wiki/1988_United_States_presidential_election" title="1988 United States presidential election">1988</a>
</th>
<th style="text-align:center; width:6.67%;"><a href="/wiki/1992_United_States_president

In [55]:
data = [[cell.get_text(strip=True) for cell in cells]
        for row in table.find_all("tr")
        for cells in [row.find_all(["td", "th"])] ]

In [56]:
data

[['Year',
  '1972',
  '1976',
  '1980',
  '1984',
  '1988',
  '1992',
  '1996',
  '2000',
  '2004',
  '2008',
  '2012',
  '2016',
  '2020',
  '2024'],
 ['Democratic candidate',
  'George McGovern',
  'Jimmy Carter',
  'Jimmy Carter',
  'Walter Mondale',
  'Michael Dukakis',
  'Bill Clinton',
  'Bill Clinton',
  'Al Gore',
  'John Kerry',
  'Barack Obama',
  'Barack Obama',
  'Hillary Clinton',
  'Joe Biden',
  'Kamala Harris'],
 ['Republican candidate',
  'Richard Nixon',
  'Gerald Ford',
  'Ronald Reagan',
  'Ronald Reagan',
  'George H. W. Bush',
  'George H. W. Bush',
  'Bob Dole',
  'George W. Bush',
  'George W. Bush',
  'John McCain',
  'Mitt Romney',
  'Donald Trump',
  'Donald Trump',
  'Donald Trump'],
 ['Nationalpopular vote',
  'Nixon',
  'Carter',
  'Reagan',
  'Reagan',
  'Bush',
  'Clinton',
  'Clinton',
  'Gore',
  'Bush',
  'Obama',
  'Obama',
  'Clinton',
  'Biden',
  'Trump'],
 ['Alabama',
  'Nixon',
  'Carter',
  'Reagan',
  'Reagan',
  'Bush',
  'Bush',
  'Dole',
  

In [57]:
df = pd.DataFrame(data)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Year,1972,1976,1980,1984,1988,1992,1996,2000,2004,2008,2012,2016,2020,2024
1,Democratic candidate,George McGovern,Jimmy Carter,Jimmy Carter,Walter Mondale,Michael Dukakis,Bill Clinton,Bill Clinton,Al Gore,John Kerry,Barack Obama,Barack Obama,Hillary Clinton,Joe Biden,Kamala Harris
2,Republican candidate,Richard Nixon,Gerald Ford,Ronald Reagan,Ronald Reagan,George H. W. Bush,George H. W. Bush,Bob Dole,George W. Bush,George W. Bush,John McCain,Mitt Romney,Donald Trump,Donald Trump,Donald Trump
3,Nationalpopular vote,Nixon,Carter,Reagan,Reagan,Bush,Clinton,Clinton,Gore,Bush,Obama,Obama,Clinton,Biden,Trump
4,Alabama,Nixon,Carter,Reagan,Reagan,Bush,Bush,Dole,Bush,Bush,McCain,Romney,Trump,Trump,Trump
5,Alaska,Nixon,Ford,Reagan,Reagan,Bush,Bush,Dole,Bush,Bush,McCain,Romney,Trump,Trump,Trump
6,Arizona,Nixon,Ford,Reagan,Reagan,Bush,Bush,Clinton,Bush,Bush,McCain,Romney,Trump,Biden,Trump
7,Arkansas,Nixon,Carter,Reagan,Reagan,Bush,Clinton,Clinton,Bush,Bush,McCain,Romney,Trump,Trump,Trump
8,California,Nixon,Ford,Reagan,Reagan,Bush,Clinton,Clinton,Gore,Kerry,Obama,Obama,Clinton,Biden,Harris
9,Colorado,Nixon,Ford,Reagan,Reagan,Bush,Clinton,Dole,Bush,Bush,Obama,Obama,Clinton,Biden,Harris
